### ISSUE TITLE
JMC cannot be opened on macOS 10.15.6

### ISSUE THREAD

**Issue by florianmutter** [adoptium/jmc-build#14]
Trying to open version 7.1.1 or 8.0.0-SNAPSHOT gives the following error: "JDK Mission Control is damaged and can’t be opened. You should move it to the Trash". It cannot be used.

**Comment by reinhapa** [comment]
@florianmutter have you unpacked the tar.gz binary as documented here: https://adoptopenjdk.net/jmc.html ?

**Comment by florianmutter** [comment]
Ha didn't see that. Now I still cant start it but now it is because of jenv (https://github.com/AdoptOpenJDK/openjdk-support/issues/123). Thank you very much
