### ISSUE TITLE
Publish to sdkman

### ISSUE THREAD

**Issue by agilob** [adoptium/jmc-build#25]
Could you guys please publish jmc to sdkman?

I know this isn't the right repo, but I couldnt find any better.

**Comment by poconnor-lab49** [comment]
I'd like to see this too.  Interestingly, sdkman now lists an `8.0.0-adpt` version as available for JMC. It would be great if this was updated for new releases.

I see [a PR in the sdkman-db-migrations repo](https://github.com/sdkman/sdkman-db-migrations/pull/534/files) to add it, but it doesn't seem to [follow the current onboarding advice](https://github.com/sdkman/sdkman-cli/wiki/Vendor-onboarding-process#create-the-new-candidate), so maybe unrelated?

Looks like whatever is currently available from SDKMAN is configured to download from https://github.com/AdoptOpenJDK/openjdk-jmc-overrides/releases/download/8.0.0/org.openjdk.jmc-8.0.0-linux.gtk.x86_64.tar.gz , which then redirects here, so I'm guessing its out of date.

**Comment by iceofst** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by agilob** [comment]
sdkman has jmc now, but leading version is from zulu and it's still out of date, so I created an aur package for archlinux https://aur.archlinux.org/packages/jmc-adoptium

**Comment by iceofst** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
