### ISSUE TITLE
Decide if Eclipse Mission Control should override branding

### ISSUE THREAD

**Issue by thegreystone** [adoptium/jmc-build#38]
Someone will have to decide if Eclipse Mission Control should have its own branding. This can, for example, include overriding things like:

- The application name (JDK Mission Control -> Eclipse Mission Control)
- The splash screen
- The application icon

**Comment by thegreystone** [comment]
@reinhapa - I am not quite sure who will make that decision. Do you know?

**Comment by reinhapa** [comment]
@karianna I could think, that @gdams  would have an idea, when he is back from his vacation. Until then I will give it a try to have an GPG signed distribution (#39) being done during the build.

**Comment by thegreystone** [comment]
This has been decided now, so we can close this one. Pretty new splash and all.
