### ISSUE TITLE
plz add brew

### ISSUE THREAD

**Issue by leonardwoo** [adoptium/jmc-build#40]
Plz add this project to brew cask

**Comment by thegreystone** [comment]
I think @bric3 has done that.

**Comment by bric3** [comment]
Yes. I added the formula to brew ~3years ago to the main repo https://github.com/Homebrew/homebrew-cask/commits/master/Casks/jdk-mission-control.rb

But I keep a separate formula for snapshots in a personal "tap". Unfortunately at the moment the latest snapshot published dates back to November 2022.

```
brew tap bric3/tap
brew install jdk-mission-control-snapshot
```


https://github.com/bric3/homebrew-tap

**Comment by reinhapa** [comment]
@bric3 where do you check for those updates?

**Comment by bric3** [comment]
@reinhapa I'm tracking the snapshot releases on this github project:

https://github.com/adoptium/jmc-build/releases

**Comment by reinhapa** [comment]
Seems, that the scheduled builds are disabled  (@gdams could you check that) and I do not have access to re-enable them...

**Comment by reinhapa** [comment]
@bric3 I'm in the process of setting up the [Eclipse CI build instance ](https://ci.eclipse.org/mc/) in order to solve #39. There is currently a  jmc-pipeline build task that produces [nighlty built artifacts](https://ci.eclipse.org/mc/job/jmc-pipeline/lastSuccessfulBuild/artifact/target/products/) that you might could refer in the meantime...

**Comment by bric3** [comment]
Thank you!

**Comment by reinhapa** [comment]
@bric3 where would I have to change the snapshot URL for brew, in case I change the location in the future?

**Comment by bric3** [comment]
@reinhapa So the snapshot formula is not on homebrew itself but in my tap.

https://github.com/bric3/homebrew-tap/blob/main/Casks/jdk-mission-control-snapshot.rb

**Comment by reinhapa** [comment]
@bric3 would you mind providing an official Adoptium variant?

**Comment by bric3** [comment]
Clearly I don't mind using an adoptium variant, especially for a snapshot. This formula was based on the github releases before.

For the main formula on homebrew it's getting the one coming from java.net.

Do you have links ?

**Comment by reinhapa** [comment]
> Do you have links ?

What kind of links do you need? (sorry for the delay)

**Comment by bric3** [comment]
Basically any snapshot links (and I'm OK for adoptium builds of course),
before I used the snapshot builds that were on github.

Brice
