### ISSUE TITLE
JMC not available for linux aarch64

### ISSUE THREAD

**Issue by jborgers** [adoptium/jmc-build#46]
I'd like to run JMC on my linux on Apple M1.

**Comment by iceofst** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jborgers** [comment]
For those wondering what the above means, like me :-). Translation says:

This is a vacation auto-reply email from QQ mailbox. Hi, I am currently on vacation and cannot reply to your email personally. I will get back to you as soon as possible after the holiday.

**Comment by jiekang** [comment]
This would be an issue for the JMC project itself (https://github.com/openjdk/jmc), though they use the OpenJDK Jira (https://bugs.openjdk.org/projects/JMC/) so you might not be able to open an issue there. Maybe try an email to jmc-dev mailing list? https://mail.openjdk.org/mailman/listinfo/jmc-dev

**Comment by iceofst** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by thegreystone** [comment]
The JMC project _is_ built for aarch64. Here is to run it after you've built it:
target/products/org.openjdk.jmc/macosx/cocoa/aarch64/JDK\ Mission\ Control.app/Contents/MacOS/jmc

You will also find it in the Adoptium builds of JMC:
https://github.com/adoptium/jmc-build/releases

Have fun on your M1! :)

**Comment by jborgers** [comment]
Hi @thegreystone thanks for your reply. However, I can only find an aarch64 build for MacOS, not for Linux. 
Is it available for Linux?

Thanks

**Comment by iceofst** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by thegreystone** [comment]
Ah! I missed that you wanted it for Linux. Sorry.

I added:
https://bugs.openjdk.org/browse/JMC-8120

**Comment by thegreystone** [comment]
So, I did a PR, that I believe should work. That said, I don't have Linux on an M1, so I can't verify. Could you help give it a shot? 

It's over here:
https://github.com/openjdk/jmc/pull/514

**Comment by jborgers** [comment]
Hi @thegreystone, thanks for doing the work. 
I fetched the code from your clone and finally managed to build/package it locally. However, I see 4 products in target and the linux aarch64 is missing. 
Do I need to configure somewhere that I also want to create that product?

**Comment by jborgers** [comment]
I was using master branch. Will try again with branch 8120-linux-aarch64.

**Comment by jborgers** [comment]
It seems to work! JMC starts up, JMX browser works, I will test the flight recording later.

**Comment by jborgers** [comment]
Flight recorder with reports also works! :-) 
Nice to see more colors in flame graphs. 
Only, just 'Samples' metric seems to work for flame graph.

**Comment by thegreystone** [comment]
> It seems to work! JMC starts up, JMX browser works, I will test the flight recording later.

Excellent! :)

**Comment by reinhapa** [comment]
@thegreystone we may leave this issue open, as the new binary needs to be incorporated into the build scripts...

**Comment by reinhapa** [comment]
Binaries now available on https://adoptium.net/jmc/

**Comment by thegreystone** [comment]
Nice!
