### ISSUE TITLE
https://adoptium.net/jmc/ page points to or names incorrect aarch64 binaries.

### ISSUE THREAD

**Issue by stooke** [adoptium/jmc-build#47]
Under 8.3, macOS (aarch_64) names binary org.openjdk.jmc-8.3.0-macosx.cocoa.x86_64.tar.gz but points to the aarch64 binary https://github.com/adoptium/jmc-build/releases/download/8.3.0/org.openjdk.jmc-8.3.0-macosx.cocoa.aarch64.tar.gz

Under 9.0.0, macOS (aarch64) names org.openjdk.jmc-9.0.0-SNAPSHOT-macosx.cocoa.aarch_64.tar.gz but points to https://github.com/adoptium/jmc-build/releases/download/9.0.0-SNAPSHOT/org.openjdk.jmc-9.0.0-SNAPSHOT-macosx.cocoa.x86_64.tar.gz

**Comment by reinhapa** [comment]
@stooke thanks for the feedback, I will look into that.

**Comment by reinhapa** [comment]
Fixed links in the adoptium website.
