### ISSUE TITLE
StackOverflowError when integrating JMC in Eclipse with FlatScrollBar on "Threads" page.

### ISSUE THREAD

**Issue by RoiSoleil** [adoptium/jmc-build#55]
I get a StackOverflowError when integrating JMC in Eclipse with FlatScrollBar on "Threads" page.

No problem with "(Legacy) Threads" page ...

![image](https://github.com/adoptium/jmc-build/assets/3462260/a125e8a3-1c7f-4351-8eff-5f91bd3f13a1)

![image](https://github.com/adoptium/jmc-build/assets/3462260/9f33d7e3-0fb2-4528-80b0-926535d9fad8)

**Comment by reinhapa** [comment]
@RoiSoleil this is not a build issue and needs to be reported at [bugs.openjdk.org](https://bugs.openjdk.org/secure/Dashboard.jspa).

**Comment by aptmac** [comment]
I've opened a bug for this over at: https://bugs.openjdk.org/browse/JMC-8148

My initial thought is that the FlatScrollBar functionality is interfering with the Threads page code that syncs the scrollbars on the two canvas components, but I'll have to take a look sometime to see if that is the case.
