### ISSUE TITLE
SNAPSHOT build is not usable since commit https://github.com/openjdk/jmc/commit/8635f415e507a6ef876b540fffc6d8ea3c21ef42

### ISSUE THREAD

**Issue by RoiSoleil** [adoptium/jmc-build#57]
SNAPSHOT build is not usable since commit https://github.com/openjdk/jmc/commit/8635f415e507a6ef876b540fffc6d8ea3c21ef42

**Comment by iceofst** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by aptmac** [comment]
What's the error message? There were quite a few files changed, it might require a clean installation.

**Comment by RoiSoleil** [comment]
There is a problem with org.openjdk.jmc.rjmx.common when i'm trying to install it it with the update site in Eclipse

**Comment by aptmac** [comment]
Ah, that would probably do it. It doesn't look like the update site has been updated.

Edit: is there an update site? I see https://github.com/adoptium/jmc-build/issues/29 is still open..

Edit2: it looks like there were update sites, the links are now dead and weren't up to the current JMC version anyways

**Comment by RoiSoleil** [comment]
It ok now with https://github.com/openjdk/jmc/pull/545
