### ISSUE TITLE
Artifact names no longer include versions

### ISSUE THREAD

**Issue by jiekang** [adoptium/jmc-build#67]
Since 9.0.0 SNAPSHOT and 9.0.0, the tarballs no longer have versions:

8.3.0: [org.openjdk.jmc-8.3.0-linux.gtk.x86_64.tar.gz](https://github.com/adoptium/jmc-build/releases/download/8.3.0/org.openjdk.jmc-8.3.0-linux.gtk.x86_64.tar.gz)

9.0.0-SNAPSHOT: [org.openjdk.jmc-linux.gtk.x86_64.tar.gz](https://github.com/adoptium/jmc-build/releases/download/9.0.0-SNAPSHOT/org.openjdk.jmc-linux.gtk.x86_64.tar.gz)

9.0.0: [org.openjdk.jmc-linux.gtk.x86_64.tar.gz](https://github.com/adoptium/jmc-build/releases/download/9.0.0/org.openjdk.jmc-linux.gtk.x86_64.tar.gz)

This is slightly annoying as after downloading, you do not know what version the tarball is without more examination, and the names can collide.

**Comment by jiekang** [comment]
Possibly introduced in https://github.com/adoptium/jmc-build/commit/cb7a1963df4e8f4231a07161e7843a7f95447e67

**Comment by reinhapa** [comment]
@gdams any way to set the version again using the replaced githib action?

**Comment by jiekang** [comment]
Oh neat! Thank you @gdams!
