### ISSUE TITLE
Build for 9.1.0-SNAPSHOT isn't working in Github

### ISSUE THREAD

**Issue by RoiSoleil** [adoptium/jmc-build#81]
The build is failing with :

![image](https://github.com/user-attachments/assets/cd8d0960-0fd0-4d6b-bc7e-27310ed4f878)

I checked the log and the package is already containing version, so you could remove this step :

![image](https://github.com/user-attachments/assets/60c32ac2-2dd1-4c4f-8792-dfa3cbdd2bdb)

**Comment by RoiSoleil** [comment]
@reinhapa

**Comment by aptmac** [comment]
This is a recent upstream change, the version is now added to the tarball: https://bugs.openjdk.org/browse/JMC-8231
