### ISSUE TITLE
Provide 9.0.0 stable build

### ISSUE THREAD

**Issue by sdavids** [adoptium/jmc-build#83]
> Final Eclipse Mission Control 8.3.0 (latest stable)

https://adoptium.net/jmc/

> 9.0.0
>
> 2024-01-24	Source Release

https://wiki.openjdk.org/display/jmc/Releases

**Comment by aptmac** [comment]
I think the Adoptium page just needs an update to point at the links, the 9.0.0 build has been available since April: https://github.com/adoptium/jmc-build/releases/tag/9.0.0

**Comment by jiekang** [comment]
Updates needed specifically here: https://github.com/adoptium/adoptium.net/blob/main/content/asciidoc-pages/jmc/index.adoc

**Comment by jiekang** [comment]
Should be fixed now via https://github.com/adoptium/adoptium.net/pull/3015

Thank you @reinhapa!

**Comment by jiekang** [comment]
Though it seems I don't have permissions to close this issue... If someone else can, that would be helpful, thanks!

**Comment by reinhapa** [comment]
Fixed Adoptium site
